name: MSDO

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  sample:
    name: Microsoft Security DevOps
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
